name: labcoin
description: A Cryptocurrency to for Oberlab Holzkirchen
version: 0.0.1
author: Konstantin Ullrich <konstantinullrich12@gmail.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.2
  crypto: ^2.1.3
  http: ^0.12.0+2
  crypton: ^1.0.1
  webservant: ^0.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
